### ISSUE TITLE
Why a statefulset is being used instead of a deployment/deploymentConfig ? 

### ISSUE THREAD

**Issue by Haithamk22** [wildfly/wildfly-operator#232]

**Comment by yersan** [comment]
Hello @Haithamk22 

The wildfly operator uses StatefulSets because its use case is to address these application requirements:

- Stable, unique network identifiers.
- Stable, persistent storage.
- Ordered, graceful deployment and scaling.
- Ordered, automated rolling updates.
- Persistent storage for transactions.

If your application doesn't have those requirements, you should take a look at the [WildFly Helm Charts](https://github.com/wildfly/wildfly-charts) to deploy your applications. WildFly Helm Charts uses deployment/deploymentConfig instead of StatefulSets.
